#!/usr/bin/env python3
"""
Training script for GAT-based colon cancer metastasis classification (N0 vs N1).

Loads pre-built PyG graphs from outputs/graphs/train/ and outputs/graphs/val/
(generated by scripts/build_dataset.py) and trains a Graph Attention Network
with wandb logging, AMP, weighted loss, early stopping, and checkpointing.

Prerequisites:
    1. python scripts/build_dataset.py      # generate the .pt graph files
    2. wandb login                          # authenticate (see bottom of this file)

Usage:
    python train.py
    python train.py --epochs 100 --batch_size 16 --lr 1e-4 --hidden 256 --heads 4
    python train.py --graphs_dir outputs/graphs --run_name experiment_01 --seed 42
"""

import argparse
import copy
import random
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
import wandb
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score, roc_auc_score,
)
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GATConv, global_max_pool, global_mean_pool
from tqdm import tqdm


# ── reproducibility ────────────────────────────────────────────────────────────

def fix_seeds(seed: int = 123) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark     = False


# ── early stopping ─────────────────────────────────────────────────────────────
# Adapted from pt1diagnosis/CodeTFGVAEs/TrainModels/EarlyStopping.py

class EarlyStopping:
    """Stop training if val_loss does not improve after `patience` epochs
    (ignored during the first `warm_up` epochs)."""

    def __init__(self, warm_up: int = 10, patience: int = 20, delta: float = 0.0):
        self.warm_up    = warm_up
        self.patience   = patience
        self.delta      = delta
        self.counter    = 0
        self.best_score = float("inf")
        self.best_model = None
        self.epoch      = 0
        self.early_stop = False

    def __call__(self, epoch: int, val_loss: float, model: torch.nn.Module) -> bool:
        score = round(val_loss, 4)
        if epoch > self.warm_up:
            if score < self.best_score - self.delta:
                self.best_score = score
                self.best_model = copy.deepcopy(model)
                self.epoch      = epoch
                self.counter    = 0
            else:
                self.counter += 1
                if self.counter >= self.patience:
                    self.early_stop = True
        return self.early_stop


# ── model ──────────────────────────────────────────────────────────────────────

class GATClassifier(torch.nn.Module):
    """
    Three-layer GAT with concat(global_mean_pool, global_max_pool) and an MLP head.

    Architecture:
        GATConv(in → hidden, heads) → BN → ELU
        GATConv(hidden*heads → hidden, heads) → BN → ELU
        GATConv(hidden*heads → hidden, 1) → BN → ELU
        global_mean_pool || global_max_pool  →  hidden*2
        Linear(hidden*2 → hidden) → ReLU → Dropout
        Linear(hidden → 2)
    """

    def __init__(self, in_channels: int, hidden: int, heads: int, dropout: float):
        super().__init__()
        self.dropout = dropout

        self.conv1 = GATConv(in_channels,   hidden, heads=heads, concat=True,  dropout=dropout)
        self.bn1   = torch.nn.BatchNorm1d(hidden * heads)

        self.conv2 = GATConv(hidden * heads, hidden, heads=heads, concat=True, dropout=dropout)
        self.bn2   = torch.nn.BatchNorm1d(hidden * heads)

        self.conv3 = GATConv(hidden * heads, hidden, heads=1,     concat=False, dropout=dropout)
        self.bn3   = torch.nn.BatchNorm1d(hidden)

        self.mlp = torch.nn.Sequential(
            torch.nn.Linear(hidden * 2, hidden),
            torch.nn.ReLU(),
            torch.nn.Dropout(dropout),
            torch.nn.Linear(hidden, 2),
        )

    def forward(self, x, edge_index, batch):
        x = F.elu(self.bn1(self.conv1(x, edge_index)))
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = F.elu(self.bn2(self.conv2(x, edge_index)))
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = F.elu(self.bn3(self.conv3(x, edge_index)))
        x = torch.cat([global_mean_pool(x, batch),
                        global_max_pool(x, batch)], dim=1)   # (B, hidden*2)
        return self.mlp(x)                                    # (B, 2)


# ── dataset helpers ────────────────────────────────────────────────────────────

def load_graphs(split_dir: Path) -> list[Data]:
    """Load all .pt graph files from a directory."""
    paths = sorted(split_dir.glob("*.pt"))
    if not paths:
        sys.exit(f"[ERROR] No .pt files found in {split_dir}")
    graphs = []
    for p in tqdm(paths, desc=f"Loading {split_dir.name}", unit="graph", leave=False):
        graphs.append(torch.load(p, weights_only=False))
    print(f"[INFO] {split_dir.name}: {len(graphs)} graphs loaded")
    return graphs


def compute_class_weights(graphs: list[Data]) -> torch.Tensor:
    """Inverse-frequency class weights for CrossEntropyLoss (handles class imbalance)."""
    labels = np.array([g.y.item() for g in graphs])
    counts = np.bincount(labels, minlength=2).astype(float)
    weights = 1.0 / np.where(counts == 0, 1.0, counts)
    weights /= weights.sum()
    return torch.tensor(weights, dtype=torch.float32)


def make_weighted_sampler(graphs: list[Data]) -> torch.utils.data.WeightedRandomSampler:
    """WeightedRandomSampler for balanced mini-batches (adapted from pt1diagnosis datasets.py)."""
    labels  = np.array([g.y.item() for g in graphs])
    counts  = np.bincount(labels, minlength=2).astype(float)
    class_w = torch.tensor(1.0 / np.where(counts == 0, 1.0, counts), dtype=torch.float32)
    sample_w = class_w[labels]
    return torch.utils.data.WeightedRandomSampler(
        weights=sample_w, num_samples=len(sample_w), replacement=True
    )


# ── train / val loops ──────────────────────────────────────────────────────────

def train_epoch(
    model: torch.nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: torch.nn.Module,
    scaler: torch.amp.GradScaler,
    device: torch.device,
) -> dict:
    model.train()
    total_loss = 0.0
    all_true, all_pred, all_scores = [], [], []

    for batch in loader:
        batch = batch.to(device)
        optimizer.zero_grad()

        with torch.amp.autocast("cuda", enabled=device.type == "cuda"):
            logits = model(batch.x, batch.edge_index, batch.batch)
            loss   = criterion(logits, batch.y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item()
        probs = F.softmax(logits.detach(), dim=1)
        all_true.extend(batch.y.cpu().tolist())
        all_pred.extend(probs.argmax(dim=1).cpu().tolist())
        all_scores.extend(probs[:, 1].cpu().tolist())

    n = len(loader)
    return {
        "loss": total_loss / n,
        "acc":  accuracy_score(all_true, all_pred),
    }


@torch.no_grad()
def val_epoch(
    model: torch.nn.Module,
    loader: DataLoader,
    criterion: torch.nn.Module,
    device: torch.device,
) -> dict:
    model.eval()
    total_loss = 0.0
    all_true, all_pred, all_scores = [], [], []

    for batch in loader:
        batch  = batch.to(device)
        logits = model(batch.x, batch.edge_index, batch.batch)
        loss   = criterion(logits, batch.y)

        total_loss += loss.item()
        probs = F.softmax(logits, dim=1)
        all_true.extend(batch.y.cpu().tolist())
        all_pred.extend(probs.argmax(dim=1).cpu().tolist())
        all_scores.extend(probs[:, 1].cpu().tolist())

    n = len(loader)
    try:
        auc = roc_auc_score(all_true, all_scores)
    except ValueError:
        auc = float("nan")

    return {
        "loss":        total_loss / n,
        "acc":         accuracy_score(all_true, all_pred),
        "auc":         auc,
        "recall_N0":   recall_score   (all_true, all_pred, pos_label=0, zero_division=0),
        "recall_N1":   recall_score   (all_true, all_pred, pos_label=1, zero_division=0),
        "precision_N0":precision_score(all_true, all_pred, pos_label=0, zero_division=0),
        "precision_N1":precision_score(all_true, all_pred, pos_label=1, zero_division=0),
        "f1_N0":       f1_score       (all_true, all_pred, pos_label=0, zero_division=0),
        "f1_N1":       f1_score       (all_true, all_pred, pos_label=1, zero_division=0),
    }


# ── checkpoint ─────────────────────────────────────────────────────────────────

def save_checkpoint(
    model: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    epoch: int,
    val_auc: float,
    path: Path,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "epoch":      epoch,
            "val_auc":    val_auc,
            "model":      model.state_dict(),
            "optimizer":  optimizer.state_dict(),
        },
        path,
    )


# ── CLI ────────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Train GAT for colon cancer N0/N1 classification.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    # data
    p.add_argument("--graphs_dir",   default="outputs/graphs",
                   help="Root directory with train/ and val/ subfolders of .pt files")
    p.add_argument("--checkpoint_dir", default="outputs/checkpoints",
                   help="Directory where the best model checkpoint is saved")
    # model
    p.add_argument("--hidden",   type=int,   default=128,  help="Hidden dim per GAT head")
    p.add_argument("--heads",    type=int,   default=4,    help="Number of attention heads")
    p.add_argument("--dropout",  type=float, default=0.3,  help="Dropout rate")
    # optimiser
    p.add_argument("--lr",       type=float, default=1e-4, help="Initial learning rate")
    p.add_argument("--epochs",   type=int,   default=100,  help="Maximum training epochs")
    p.add_argument("--batch_size",type=int,  default=16,   help="Graphs per mini-batch")
    p.add_argument("--t_max",    type=int,   default=50,
                   help="T_max for CosineAnnealingLR (set to epochs if unsure)")
    # early stopping
    p.add_argument("--warm_up",  type=int,   default=10,   help="Epochs before early stopping activates")
    p.add_argument("--patience", type=int,   default=20,   help="Early stopping patience (epochs)")
    # misc
    p.add_argument("--seed",     type=int,   default=123,  help="Random seed")
    p.add_argument("--run_name", default=None, help="wandb run name (auto-generated if omitted)")
    p.add_argument("--project",  default="colon-cancer-gnn", help="wandb project name")
    return p.parse_args()


# ── main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    args   = parse_args()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    fix_seeds(args.seed)

    # ── wandb ──────────────────────────────────────────────────────────────────
    run = wandb.init(
        project=args.project,
        name=args.run_name,
        config=vars(args),
    )
    print(f"[INFO] wandb run : {run.name}  ({run.url})")

    # ── data ───────────────────────────────────────────────────────────────────
    graphs_dir = Path(args.graphs_dir)
    train_graphs = load_graphs(graphs_dir / "train")
    val_graphs   = load_graphs(graphs_dir / "val")

    class_weights = compute_class_weights(train_graphs).to(device)
    sampler       = make_weighted_sampler(train_graphs)

    train_loader = DataLoader(
        train_graphs, batch_size=args.batch_size, sampler=sampler,
    )
    val_loader = DataLoader(
        val_graphs, batch_size=args.batch_size, shuffle=False,
    )

    n_train = len(train_graphs)
    n_val   = len(val_graphs)
    in_ch   = train_graphs[0].x.shape[1]
    print(f"[INFO] Train graphs : {n_train}  |  Val graphs : {n_val}  |  Node features : {in_ch}")
    print(f"[INFO] Class weights (N0/N1) : {class_weights.cpu().numpy().round(4)}")

    # ── model ──────────────────────────────────────────────────────────────────
    model = GATClassifier(
        in_channels=in_ch,
        hidden=args.hidden,
        heads=args.heads,
        dropout=args.dropout,
    ).to(device)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"[INFO] Model params : {n_params:,}")
    wandb.config.update({"n_params": n_params, "in_channels": in_ch}, allow_val_change=True)

    # ── optimiser & scheduler ──────────────────────────────────────────────────
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.t_max, eta_min=1e-6
    )
    criterion = torch.nn.CrossEntropyLoss(weight=class_weights)
    scaler    = torch.amp.GradScaler("cuda", enabled=device.type == "cuda")

    early_stopping  = EarlyStopping(warm_up=args.warm_up, patience=args.patience)
    best_val_auc    = 0.0
    best_epoch      = 0
    ckpt_path       = Path(args.checkpoint_dir) / f"{run.name}_best.pt"

    print(f"\n[INFO] Device : {device}")
    if device.type == "cuda":
        print(f"[INFO] GPU    : {torch.cuda.get_device_name(0)}")
        print(f"[INFO] VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    print(f"\nTraining for up to {args.epochs} epochs ...\n")
    t0 = time.time()

    # ── training loop ──────────────────────────────────────────────────────────
    for epoch in range(1, args.epochs + 1):
        tr = train_epoch(model, train_loader, optimizer, criterion, scaler, device)
        va = val_epoch(model, val_loader, criterion, device)
        scheduler.step()

        lr_now = scheduler.get_last_lr()[0]

        # ── wandb logging ──────────────────────────────────────────────────────
        wandb.log({
            "epoch":           epoch,
            "lr":              lr_now,
            "train/loss":      tr["loss"],
            "train/acc":       tr["acc"],
            "val/loss":        va["loss"],
            "val/acc":         va["acc"],
            "val/auc":         va["auc"],
            "val/recall_N0":   va["recall_N0"],
            "val/recall_N1":   va["recall_N1"],
            "val/precision_N0":va["precision_N0"],
            "val/precision_N1":va["precision_N1"],
            "val/f1_N0":       va["f1_N0"],
            "val/f1_N1":       va["f1_N1"],
        })

        print(
            f"Epoch {epoch:3d}/{args.epochs}  "
            f"lr={lr_now:.2e}  "
            f"train_loss={tr['loss']:.4f}  train_acc={tr['acc']:.3f}  "
            f"val_loss={va['loss']:.4f}  val_acc={va['acc']:.3f}  "
            f"val_auc={va['auc']:.4f}"
        )

        # ── checkpoint: save best model by val AUC ─────────────────────────────
        if va["auc"] > best_val_auc:
            best_val_auc = va["auc"]
            best_epoch   = epoch
            save_checkpoint(model, optimizer, epoch, best_val_auc, ckpt_path)
            wandb.summary["best_val_auc"]  = best_val_auc
            wandb.summary["best_epoch"]    = best_epoch
            print(f"         ↳ new best val AUC {best_val_auc:.4f} — checkpoint saved")

        # ── early stopping ─────────────────────────────────────────────────────
        if early_stopping(epoch, va["loss"], model):
            print(f"\n[INFO] Early stopping at epoch {epoch} (patience={args.patience})")
            break

    elapsed = time.time() - t0
    h, m, s = int(elapsed // 3600), int((elapsed % 3600) // 60), int(elapsed % 60)

    print(f"\n── Training finished ───────────────────────────────────────────────")
    print(f"  Total time        : {h}h {m}m {s}s")
    print(f"  Best val AUC      : {best_val_auc:.4f}  (epoch {best_epoch})")
    print(f"  Checkpoint        : {ckpt_path.resolve()}")

    wandb.finish()


if __name__ == "__main__":
    main()
